Cache action object instead of string
mantidproject/mslice pull request #903
Opened 2023-04-28 09:00 UTC by robertapplin

**Description of work:**
This PR fixes a crash caused by caching a string rather than an action object. This causes a crash when calling `setChecked` on the string rather than on the action object.

**To test:**
1. Create a cut plot
2. change intensity to Chi"(Q,E) but click on cancel
3. There should be no crash. The intensity should remain the same

Part of #854

2023-05-02 14:47 UTC, MialLewis requested changes

2023-05-02 14:49 UTC, MialLewis commented
The fix as is solves the exception in question, but causes an error to be thrown in a few other places.

I've pushed a change which I suggest as an alternative fix.

The code I've changed here is a hangover from when action objects themselves used to be cached that slipped through the net.

2023-05-02 15:36 UTC, robertapplin reviewed
Looks good, your fix is much better. I can't approve this PR unfortunately as I am the original Author

2023-05-03 09:51 UTC, SilkeSchomann approved these changes
The fix works well 👍

2023-05-03 09:52 UTC, merged